### ISSUE TITLE
Saving Files

### ISSUE THREAD

**Issue by delyke** [bayareawebpro/laravel-multistep-forms#31]
Hello! I have a file input on my form, and when i trying to save form result I have an error:

`Serialization of 'Illuminate\Http\UploadedFile' is not allowed`

My code: 

` <div class="card text-left  mt-3">
                <h6 class="card-header" style="font-size: 15px">Information</h6>
                <div class="card-body d-flex">
                    <div class="form-group w-75 mr-1">
                        <label for="requirements">Requirements</label>
                        <div class="input-group mb-3">
                            <textarea name="requirements" class="editor">{{$form->getValue('requirements')}}</textarea>
                        </div>
                    </div>
                    <div class="form-group w-25">
                        <label for="basic-url">Files</label>
                        <input type="file" name="filefield" multiple="multiple">
                    </div>
                </div>
            </div>`

`->addStep(2, [
			'rules' => [
				'title' => 'required|string',
				'requirements' => 'required',
				'finish' => 'string',
				'filefield' => 'nullable|mimes:jpg,jpeg,png',
				'tags' => 'nullable|string'
			],
		])`

How fix it?

**Comment by bayareawebpro** [comment]
A new `beforeSave` callback has been added.   Please update the package to pull down this addition.

```php
    // Modify data before saved to session after each step.
    ->beforeSave(function(array $data) {
    
        // Transform non-serializable objects to paths, array data etc...
        return $data;
    })

```

**Comment by delyke** [comment]
`syntax error, unexpected '|', expecting variable (T_VARIABLE)`

after update package to version 1.1.0
![image](https://user-images.githubusercontent.com/103931543/185858208-c62246cc-e294-4e98-a4fc-8d5995d051b8.png)
