### ISSUE TITLE
Elaborate on the documentations

### ISSUE THREAD

**Issue by spiritkiddie** [bayareawebpro/laravel-multistep-forms#37]
Its hard to get your head around at first glance, the documentations doesnt specify where the examples given should be, whether in controller or a separate class. can you please save some time to work on the documentation step by step to make it easy for especially beginners.

Also from what i understand rendering and storing forms will be handled by same controller method so if you are using default laravel resources methods like index,create,store etc. you get errors with the route.

Well done with this package too it saves alot of time.

**Comment by bayareawebpro** [comment]
Normally you would just return it from a controller method (already mentioned by the first sentence on the README.md).   

This is designed for public facing forms primarily.  If you want to use with resources you need to disable the built-in resource routes for the methods the form replaces, as long as every route is unique, then there will be no collisions.

Example for edit & update: 

```php
// Multi-step Route replaces create and store.  (GET /posts/create, POST /posts/create)
Route::any('posts/create')->name('posts.create'); 

// Multi-step Route replaces edit and update (GET /posts/{post}/edit, PUT or POST /posts/{post}/edit)
Route::any('posts/{post}/edit')->name('posts.edit'); 

// Only Index and Destroy needed. (GET /posts, DELETE /posts/{post)
Route::resource('posts')->only(['index', 'destroy']);
```
