### ISSUE TITLE
Values not saved unless validated

### ISSUE THREAD

**Issue by snjkg** [bayareawebpro/laravel-multistep-forms#7]
Hi, first of all this package is really useful but also simple at the same time.

For optional fields, the values don't save to $form unless you validate it (with something like nullable). Is this intended?

Thanks

**Comment by bayareawebpro** [comment]
Thanks, glad you're enjoying it. 

Yes this is intended, the issue stems from allowing non-validated inputs to be serialized in the session which is a possible vector for attacks or abuse, so I opted to enforce that all inputs have some form of validation to be saved.  Inputs are gathered from the `validated()` method.

For optional fields I recommend: 

```
[
'sometimes', // may not be present.
'nullable', // may be null value.
// other rules
]
```

If you want to access the request, you can do so in the `beforeStep` or `onStep` callbacks by accessing the request object directly from the form object:

```
->onStep(3, function (MultiStepForm $form) {
  $form->setValue('active_tab', (string) $form->request->get('active_tab', 'details'));
})
```

📝 Some additional information will be added to the ReadMe to help other users with this information the next time I work on it.  I'll close this issue, but feel free to open another if needed.  Happy to assist.

**Comment by snjkg** [comment]
Thanks
